# Generated by Django 5.2.7 on 2025-11-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('wd', models.CharField(blank=True, default='', max_length=32, verbose_name='WikiData ID')),
                ('urn', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('being', models.CharField(choices=[('mortal', 'Mortal'), ('divine', 'Divine'), ('creature', 'Mythical Creature'), ('other', 'Other')], default='mortal', max_length=16)),
                ('number', models.CharField(choices=[('individual', 'Individual'), ('collective', 'Collective')], default='individual', max_length=16)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('x', 'Mixed/non-binary'), ('none', 'Unknown/not-applicable')], default='none', max_length=16)),
                ('wd', models.CharField(blank=True, default='', max_length=32, verbose_name='WikiData ID')),
                ('manto', models.CharField(blank=True, default='', max_length=32, verbose_name='MANTO ID')),
                ('tt', models.CharField(blank=True, default='', max_length=32, verbose_name='ToposText ID')),
                ('notes', models.CharField(blank=True, default='', max_length=256, verbose_name='Notes')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('seq', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='CharacterInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('display', models.CharField(max_length=128)),
                ('being', models.CharField(choices=[('mortal', 'Mortal'), ('divine', 'Divine'), ('creature', 'Mythical Creature'), ('other', 'Other')], default='mortal', max_length=16)),
                ('number', models.CharField(choices=[('individual', 'Individual'), ('collective', 'Collective')], default='individual', max_length=16)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('x', 'Mixed/non-binary'), ('none', 'Unknown/not-applicable')], default='none', max_length=16)),
                ('disguise', models.CharField(blank=True, default='', max_length=128)),
                ('anon', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=256)),
                ('context', models.CharField(max_length=128)),
                ('char', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='speechdb.character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('type', models.CharField(choices=[('S', 'Soliloquy'), ('M', 'Monologue'), ('D', 'Dialogue'), ('G', 'General')], max_length=1)),
                ('seq', models.IntegerField()),
                ('l_fi', models.CharField(max_length=16, verbose_name='first line')),
                ('l_la', models.CharField(max_length=16, verbose_name='last line')),
                ('spkr_notes', models.CharField(blank=True, default='', max_length=256)),
                ('addr_notes', models.CharField(blank=True, default='', max_length=256)),
                ('part', models.IntegerField()),
                ('level', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=256)),
                ('addr', models.ManyToManyField(blank=True, default='', related_name='addresses', to='speechdb.characterinstance')),
                ('spkr', models.ManyToManyField(related_name='speeches', to='speechdb.characterinstance')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='speechdb.speechcluster')),
            ],
            options={
                'ordering': ['work', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='SpeechTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('type', models.CharField(choices=[('cha', 'Challenge'), ('com', 'Command'), ('con', 'Consolation'), ('del', 'Deliberation'), ('des', 'Desire and Wish'), ('exh', 'Exhortation and Self-Exhortation'), ('far', 'Farewell'), ('gre', 'Greeting and Reception'), ('inf', 'Information and Description'), ('inv', 'Invitation'), ('ins', 'Instruction'), ('lam', 'Lament'), ('lau', 'Praise and Laudation'), ('mes', 'Message'), ('nar', 'Narration'), ('ora', 'Prophecy, Oracular Speech, and Interpretation'), ('per', 'Persuasion'), ('pra', 'Prayer'), ('que', 'Question'), ('req', 'Request'), ('res', 'Reply to Question'), ('tau', 'Taunt'), ('thr', 'Threat'), ('vit', 'Vituperation'), ('vow', 'Promise and Oath'), ('war', 'Warning'), ('und', 'Undefined')], default='und', max_length=3)),
                ('doubt', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=128)),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='speechdb.speech')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('wd', models.CharField(blank=True, default='', max_length=32, verbose_name='WikiData ID')),
                ('tlg', models.CharField(blank=True, default='', max_length=12)),
                ('urn', models.CharField(blank=True, default='', max_length=128)),
                ('lang', models.CharField(choices=[('greek', 'Greek'), ('latin', 'Latin')], max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speechdb.author')),
            ],
            options={
                'ordering': ['author', 'title'],
            },
        ),
        migrations.AddField(
            model_name='speech',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speechdb.work'),
        ),
    ]
