# Generated by Django 3.1.13 on 2024-04-04 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('wd', models.CharField(max_length=32, verbose_name='WikiData ID')),
                ('urn', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('being', models.CharField(choices=[('mortal', 'Mortal'), ('divine', 'Divine'), ('creature', 'Mythical Creature'), ('other', 'Other')], default='mortal', max_length=16)),
                ('number', models.CharField(choices=[('individual', 'Individual'), ('collective', 'Collective'), ('other', 'Other')], default='individual', max_length=16)),
                ('gender', models.CharField(choices=[('none', 'Unknown/not-applicable'), ('x', 'Mixed/non-binary'), ('female', 'Female'), ('male', 'Male')], default='none', max_length=16)),
                ('wd', models.CharField(max_length=32, null=True, verbose_name='WikiData ID')),
                ('manto', models.CharField(max_length=32, null=True, verbose_name='MANTO ID')),
                ('tt', models.CharField(max_length=32, null=True, verbose_name='ToposText ID')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('being', models.CharField(choices=[('mortal', 'Mortal'), ('divine', 'Divine'), ('creature', 'Mythical Creature'), ('other', 'Other')], default='mortal', max_length=16)),
                ('number', models.CharField(choices=[('individual', 'Individual'), ('collective', 'Collective'), ('other', 'Other')], default='individual', max_length=16)),
                ('gender', models.CharField(choices=[('none', 'Unknown/not-applicable'), ('x', 'Mixed/non-binary'), ('female', 'Female'), ('male', 'Male')], default='none', max_length=16)),
                ('disguise', models.CharField(max_length=128, null=True)),
                ('anon', models.BooleanField(default=False)),
                ('context', models.CharField(max_length=128)),
                ('tags', models.JSONField(default=dict)),
                ('char', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='speechdb.character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Soliloquy'), ('M', 'Monologue'), ('D', 'Dialogue'), ('G', 'General')], max_length=1)),
                ('seq', models.IntegerField()),
                ('l_fi', models.CharField(max_length=16, verbose_name='first line')),
                ('l_la', models.CharField(max_length=16, verbose_name='last line')),
                ('part', models.IntegerField()),
                ('level', models.IntegerField(default=0)),
                ('addr', models.ManyToManyField(blank=True, related_name='addresses', to='speechdb.CharacterInstance')),
            ],
            options={
                'ordering': ['work', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='SpeechCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('wd', models.CharField(max_length=32, verbose_name='WikiData ID')),
                ('tlg', models.CharField(blank=True, max_length=12)),
                ('urn', models.CharField(max_length=128)),
                ('lang', models.CharField(choices=[('greek', 'Greek'), ('latin', 'Latin')], max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speechdb.author')),
            ],
            options={
                'ordering': ['author', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SpeechTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cha', 'Challenge'), ('com', 'Command'), ('con', 'Consolation'), ('del', 'Deliberation'), ('des', 'Desire and Wish'), ('exh', 'Exhortation and Self-Exhortation'), ('far', 'Farewell'), ('gre', 'Greeting and Reception'), ('inf', 'Information and Description'), ('inv', 'Invitation'), ('ins', 'Instruction'), ('lam', 'Lament'), ('lau', 'Praise and Laudation'), ('mes', 'Message'), ('nar', 'Narration'), ('ora', 'Prophecy, Oracular Speech, and Interpretation'), ('per', 'Persuasion'), ('pra', 'Prayer'), ('que', 'Question'), ('req', 'Request'), ('res', 'Reply to Question'), ('tau', 'Taunt'), ('thr', 'Threat'), ('vit', 'Vituperation'), ('vow', 'Promise and Oath'), ('war', 'Warning'), ('und', 'Undefined')], default='und', max_length=3)),
                ('doubt', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=128, null=True)),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='speechdb.speech')),
            ],
        ),
        migrations.AddField(
            model_name='speech',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='speechdb.speechcluster'),
        ),
        migrations.AddField(
            model_name='speech',
            name='spkr',
            field=models.ManyToManyField(related_name='speeches', to='speechdb.CharacterInstance'),
        ),
        migrations.AddField(
            model_name='speech',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speechdb.work'),
        ),
    ]
