# Generated by Django 3.0.7 on 2020-06-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.CharField(choices=[('I', 'individual'), ('C', 'collective'), ('O', 'other')], default='I', max_length=1),
        ),
    ]
