# Generated by Django 3.0.7 on 2020-06-12 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('wd', models.CharField(max_length=32, verbose_name='WikiData ID')),
                ('manto', models.CharField(max_length=32, verbose_name='MANTO ID')),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='wd_id',
            new_name='wd',
        ),
        migrations.RemoveField(
            model_name='author',
            name='manto',
        ),
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speechdb.Author'),
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_fi', models.CharField(max_length=8, verbose_name='first line')),
                ('l_la', models.CharField(max_length=8, verbose_name='last line')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speechdb.Work')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SPKR', 'speaker'), ('ADDR', 'addressee')], max_length=4)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character', to='speechdb.Character')),
                ('disg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disguise', to='speechdb.Character')),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speechdb.Speech')),
            ],
        ),
    ]
