# Generated by Django 5.2.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterinstance',
            name='char',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='speechdb.character'),
        ),
    ]
