# Generated by Django 3.0.7 on 2020-06-12 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0002_auto_20200611_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterinstance',
            name='disg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disguise', to='speechdb.Character'),
        ),
    ]
