# Generated by Django 5.2.7 on 2026-02-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0002_alter_characterinstance_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterinstance',
            name='char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='speechdb.character'),
        ),
    ]
