# Generated by Django 3.0.7 on 2020-06-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0002_character_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='being',
            field=models.CharField(default='human', max_length=16),
        ),
    ]
