# Generated by Django 5.2.7 on 2026-06-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0003_alter_characterinstance_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterinstance',
            name='changed',
            field=models.CharField(choices=[('none', 'None'), ('death', 'Death'), ('deification', 'Deification'), ('disguise', 'Disguise'), ('dream', 'Dream'), ('gender', 'Gender'), ('metamorphosis', 'Metamorphosis')], default='none', max_length=16),
        ),
    ]
