# Generated by Django 3.0.7 on 2020-06-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0004_auto_20200613_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterinstance',
            name='context',
            field=models.CharField(default='Iliad', max_length=128),
            preserve_default=False,
        ),
    ]
