# Generated by Django 5.2.8 on 2026-07-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0004_characterinstance_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='embedded_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedded_speeches', to='speechdb.speech'),
        ),
    ]
