# Generated by Django 3.0.7 on 2020-06-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0005_characterinstance_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='part',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
