# Generated by Django 3.0.7 on 2020-06-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0007_auto_20200613_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='urn',
            field=models.CharField(default='todo', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech',
            name='seq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='wd',
            field=models.CharField(default='todo', max_length=32, verbose_name='WikiData ID'),
            preserve_default=False,
        ),
    ]
