# Generated by Django 3.0.7 on 2020-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0009_auto_20200624_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='manto',
            field=models.CharField(blank=True, max_length=32, verbose_name='MANTO ID'),
        ),
    ]
