# Generated by Django 3.1.8 on 2021-05-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0010_auto_20200624_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='characterinstance',
            options={'ordering': ['char']},
        ),
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['cluster__work__id', 'seq']},
        ),
        migrations.AlterModelOptions(
            name='speechcluster',
            options={'ordering': ['work', 'speech']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['author', 'title']},
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('NB', 'Non-binary'), ('F', 'Female'), ('M', 'Male')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='being',
            field=models.CharField(choices=[('human', 'Human'), ('god', 'God'), ('other', 'Other')], default='human', max_length=16),
        ),
        migrations.AlterField(
            model_name='character',
            name='manto',
            field=models.CharField(max_length=32, null=True, verbose_name='MANTO ID'),
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('collective', 'Collective'), ('other', 'Other')], default='individual', max_length=16),
        ),
        migrations.AlterField(
            model_name='character',
            name='wd',
            field=models.CharField(max_length=32, null=True, verbose_name='WikiData ID'),
        ),
        migrations.AlterField(
            model_name='speechcluster',
            name='type',
            field=models.CharField(choices=[('S', 'Soliloquy'), ('M', 'Monologue'), ('D', 'Dialogue'), ('G', 'General')], max_length=1),
        ),
    ]
