# Generated by Django 3.1.7 on 2021-03-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0010_auto_20200624_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='characterinstance',
            options={'ordering': ['char']},
        ),
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['cluster__work', 'seq']},
        ),
        migrations.AlterModelOptions(
            name='speechcluster',
            options={'ordering': ['work', 'speech']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['author', 'title']},
        ),
        migrations.AlterField(
            model_name='character',
            name='being',
            field=models.CharField(default='human', max_length=32),
        ),
        migrations.AlterField(
            model_name='character',
            name='manto',
            field=models.CharField(max_length=32, null=True, verbose_name='MANTO ID'),
        ),
        migrations.AlterField(
            model_name='character',
            name='wd',
            field=models.CharField(max_length=32, null=True, verbose_name='WikiData ID'),
        ),
        migrations.AlterField(
            model_name='speechcluster',
            name='type',
            field=models.CharField(choices=[('S', 'Soliloquy'), ('M', 'Monologue'), ('D', 'Dialogue'), ('G', 'General')], max_length=1),
        ),
    ]
