# Generated by Django 3.0.7 on 2021-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0011_auto_20210225_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, choices=[('I', 'individual'), ('C', 'collective'), ('O', 'other')], default='I', max_length=1),
        ),
    ]
