# Generated by Django 3.1.7 on 2021-03-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0011_auto_20210318_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['seq']},
        ),
    ]
