# Generated by Django 3.1.8 on 2021-05-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0011_auto_20210510_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterinstance',
            old_name='_gender',
            new_name='instgender',
        ),
    ]
