# Generated by Django 3.1.8 on 2021-06-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0012_auto_20210527_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='anon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='being',
            field=models.CharField(choices=[('mortal', 'Mortal'), ('divine', 'Divine'), ('creature', 'Mythical Creature'), ('other', 'Other')], default='mortal', max_length=16),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('non-binary', 'Non-binary'), ('female', 'Female'), ('male', 'Male')], max_length=16, null=True),
        ),
    ]
