# Generated by Django 3.0.7 on 2021-02-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0012_auto_20210225_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='manto',
            field=models.CharField(max_length=32, verbose_name='MANTO ID'),
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(choices=[('I', 'individual'), ('C', 'collective'), ('O', 'other')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='wd',
            field=models.CharField(max_length=32, verbose_name='WikiData ID'),
        ),
    ]
