# Generated by Django 3.1.8 on 2021-05-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0012_auto_20210510_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterinstance',
            name='instgender',
        ),
    ]
