# Generated by Django 3.1.7 on 2021-03-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0013_auto_20210323_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['-seq']},
        ),
    ]
