# Generated by Django 3.0.7 on 2021-02-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0013_auto_20210225_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='manto',
            field=models.CharField(max_length=32, null=True, verbose_name='MANTO ID'),
        ),
        migrations.AlterField(
            model_name='character',
            name='wd',
            field=models.CharField(max_length=32, null=True, verbose_name='WikiData ID'),
        ),
    ]
