# Generated by Django 3.1.8 on 2021-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0014_auto_20210616_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterinstance',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
