# Generated by Django 3.1.7 on 2021-03-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0015_auto_20210323_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['cluster__work__id', 'seq']},
        ),
    ]
