# Generated by Django 3.0.7 on 2021-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0015_auto_20210302_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='being',
            field=models.CharField(default='human', max_length=32),
        ),
    ]
