# Generated by Django 3.1.7 on 2021-04-15 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0016_auto_20210323_1143'),
        ('speechdb', '0016_auto_20210302_0753'),
    ]

    operations = [
    ]
