# Generated by Django 3.1.7 on 2021-04-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0017_merge_20210414_2242'),
        ('speechdb', '0011_auto_20210414_2258'),
    ]

    operations = [
    ]
