# Generated by Django 3.1.8 on 2021-06-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0017_auto_20210621_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['work', 'seq']},
        ),
        migrations.AlterModelOptions(
            name='speechcluster',
            options={'ordering': ['speech']},
        ),
        migrations.RemoveField(
            model_name='speechcluster',
            name='work',
        ),
        migrations.AddField(
            model_name='speech',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='speechdb.work'),
            preserve_default=False,
        ),
    ]
