# Generated by Django 3.1.8 on 2021-06-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0018_auto_20210621_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='lang',
            field=models.CharField(choices=[('greek', 'Greek'), ('latin', 'Latin')], default='latin', max_length=8),
            preserve_default=False,
        ),
    ]
