# Generated by Django 3.1.8 on 2021-05-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0013_remove_characterinstance_instgender'),
        ('speechdb', '0018_merge_20210414_2324'),
    ]

    operations = [
    ]
