# Generated by Django 3.1.8 on 2021-06-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0019_work_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterinstance',
            options={'ordering': ['char']},
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, choices=[('non-binary', 'Non-binary'), ('female', 'Female'), ('male', 'Male')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='being',
            field=models.CharField(blank=True, choices=[('mortal', 'Mortal'), ('divine', 'Divine'), ('creature', 'Mythical Creature'), ('other', 'Other')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='speechdb.character'),
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='disg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disguises', to='speechdb.character'),
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='gender',
            field=models.CharField(blank=True, choices=[('non-binary', 'Non-binary'), ('female', 'Female'), ('male', 'Male')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='number',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('collective', 'Collective'), ('other', 'Other')], max_length=16, null=True),
        ),
    ]
