# Generated by Django 3.1.8 on 2021-06-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0012_auto_20210527_1144'),
        ('speechdb', '0019_merge_20210510_1642'),
    ]

    operations = [
    ]
