# Generated by Django 3.1.8 on 2022-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0020_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speechcluster',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('none', 'Unknown/not-applicable'), ('x', 'Mixed/non-binary'), ('female', 'Female'), ('male', 'Male')], default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='gender',
            field=models.CharField(choices=[('none', 'Unknown/not-applicable'), ('x', 'Mixed/non-binary'), ('female', 'Female'), ('male', 'Male')], default='none', max_length=16),
        ),
    ]
