# Generated by Django 3.1.8 on 2022-03-25 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0020_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='speech',
            name='type',
        ),
        migrations.AddField(
            model_name='characterinstance',
            name='absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='characterinstance',
            name='absent_notes',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='characterinstance',
            name='dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='characterinstance',
            name='possessed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='possessions', to='speechdb.character'),
        ),
        migrations.AddField(
            model_name='speech',
            name='absent',
            field=models.ManyToManyField(blank=True, related_name='addresses_as_absent', to='speechdb.CharacterInstance'),
        ),
        migrations.AddField(
            model_name='speech',
            name='absent_num',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Single'), ('2', 'Pair'), ('∞', 'Group')], max_length=1),
        ),
        migrations.AddField(
            model_name='speech',
            name='addr_num',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Single'), ('2', 'Pair'), ('∞', 'Group')], max_length=1),
        ),
        migrations.AddField(
            model_name='speech',
            name='bystanders',
            field=models.ManyToManyField(blank=True, related_name='addresses_as_bystander', to='speechdb.CharacterInstance'),
        ),
        migrations.AddField(
            model_name='speech',
            name='bystanders_num',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Single'), ('2', 'Pair'), ('∞', 'Group')], max_length=1),
        ),
        migrations.AddField(
            model_name='speech',
            name='freq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speech',
            name='freq_notes',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='speech',
            name='manual_length',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='speech',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='partial_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speech',
            name='partial_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speech',
            name='self_addr',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='speech',
            name='spkr_num',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Single'), ('2', 'Pair'), ('∞', 'Group')], max_length=1),
        ),
        migrations.AddField(
            model_name='speechcluster',
            name='embedded_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='speechdb.speech'),
        ),
        migrations.AddField(
            model_name='speechcluster',
            name='embedded_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speechcluster',
            name='type',
            field=models.CharField(choices=[('S', 'Soliloquy'), ('M', 'Monologue'), ('D', 'Dialogue'), ('G', 'General')], default='D', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='speechdb.character'),
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='disg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disguises', to='speechdb.character'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speechdb.work'),
        ),
    ]
