# Generated by Django 3.1.8 on 2022-05-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0021_auto_20220324_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='absent_num',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='bystanders',
        ),
        migrations.AlterField(
            model_name='speech',
            name='addr_num',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('0', 'None'), ('1', 'Single'), ('∞', 'Group')], max_length=1),
        ),
        migrations.AlterField(
            model_name='speech',
            name='bystanders_num',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('0', 'None'), ('1', 'Single'), ('∞', 'Group')], max_length=1),
        ),
        migrations.AlterField(
            model_name='speech',
            name='spkr_num',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('0', 'None'), ('1', 'Single'), ('∞', 'Group')], max_length=1),
        ),
        migrations.AlterField(
            model_name='speechcluster',
            name='embedded_level',
            field=models.IntegerField(null=True),
        ),
    ]
