# Generated by Django 3.1.8 on 2022-09-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0021_auto_20220707_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
