# Generated by Django 3.1.8 on 2022-12-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0022_speech_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cha', 'Challenge'), ('Com', 'Command'), ('Con', 'Consolation'), ('Del', 'Deliberation'), ('Des', 'Desire and Wish'), ('Exh', 'Exhortation and Self-Exhortation'), ('Far', 'Farewell'), ('Gre', 'Greeting and Reception'), ('Inf', 'Information and Description'), ('Inv', 'Invitation'), ('Ins', 'Instruction'), ('Lam', 'Lament'), ('Lau', 'Praise and Laudation'), ('Mes', 'Message'), ('Nar', 'Narration'), ('Ora', 'Prophecy, Oracular Speech, and Interpretation'), ('Per', 'Persuasion'), ('Pra', 'Prayer'), ('Que', 'Question'), ('Req', 'Request'), ('Res', 'Reply to Question'), ('Tau', 'Taunt'), ('Thr', 'Threat'), ('Vit', 'Vituperation'), ('Vow', 'Promise and Oath'), ('War', 'Warning'), ('Und', 'Undefined')], max_length=3)),
                ('doubt', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=64)),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speechdb.speech')),
            ],
        ),
    ]
