# Generated by Django 3.1.8 on 2022-05-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0022_auto_20220502_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='absent_num',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('0', 'None'), ('1', 'Single'), ('∞', 'Group')], max_length=1),
        ),
        migrations.AddField(
            model_name='speech',
            name='bystanders',
            field=models.ManyToManyField(blank=True, related_name='addresses_as_bystander', to='speechdb.CharacterInstance'),
        ),
    ]
