# Generated by Django 3.1.8 on 2022-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0023_auto_20220502_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
