# Generated by Django 3.1.8 on 2022-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0025_auto_20221207_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechtag',
            name='notes',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
