# Generated by Django 3.1.8 on 2022-12-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0027_auto_20221207_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechtag',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='speechdb.speech'),
        ),
    ]
