# Generated by Django 3.1.13 on 2024-05-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speechdb', '0030_character_tt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='speechdb.speechcluster'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='l_fi',
            field=models.CharField(max_length=16, verbose_name='first line'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='l_la',
            field=models.CharField(max_length=16, verbose_name='last line'),
        ),
    ]
